<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net40;net10.0-windows</TargetFrameworks>
    <NoWarn>WFDEV006;CA1416</NoWarn>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>MemConqueror</RootNamespace>
    <AssemblyName>MemConqueror</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup>
    <Deterministic>False</Deterministic>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*.ico" />
    <EmbeddedResource Include="Resources\*.png" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net40'">
    <Reference Include="System.Management" />
    <Reference Include="Newtonsoft.Json.dll">
      <HintPath>..\lib\net40\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="ByteSizeLib.dll">
      <HintPath>..\lib\net40\ByteSizeLib.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
    <PackageReference Include="System.Management" Version="10.0.11" />
    <PackageReference Include="ByteSize" Version="2.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\MemConqueror.Lib\MemConqueror.Lib.n.csproj" />
  </ItemGroup>

</Project>
